# Alberta budget and quality-of-life evidence

This executed companion rebuilds derived data and figures from reviewed government sources. Read [REPORT.md](REPORT.md) for conclusions and row/source limitations. No composite QoL score or causal effect is estimated.

In [1]:
from pathlib import Path
import sys, subprocess, json
import pandas as pd
from IPython.display import display, Markdown
ROOT=Path.cwd()
assert (ROOT/'research/report_template.md').exists(), 'Run from Quality of Life Analysis'
print('Runtime:',sys.executable)
print('PDF extractor:',subprocess.check_output(['pdftotext','-v'],stderr=subprocess.STDOUT,text=True).splitlines()[0])

Runtime: /workspace/.venv-alberta-independent-check/bin/python
PDF extractor: pdftotext version 25.03.0

## Rebuild reviewed financial/economic sources

Rebuilds from original PDFs with definition checks; it does not download or alter original files. Historical expense cells retain the published accounting anomaly.

In [2]:
for script in ['research/budget/extract_functional_expense.py','research/living_standards/extract_living_standards.py','research/living_standards/extract_current_social_outcomes.py','research/living_standards/extract_childcare_income_access.py','research/living_standards/extract_mbm_poverty.py','research/health/life_tables/extract_life_expectancy.py','research/source_verification/extract_safety_mental_health.py','research/health/extract_health_outcomes.py','scripts/analyze_inputs.py','scripts/build_figures.py']:
    subprocess.run([sys.executable,str(ROOT/script)],cwd=ROOT,check=True)

{
  "functional_rows": 10,
  "ministry_rows": 26,
  "rounding_checks": {
    "budget_2024_25_million": 0.0,
    "actual_2024_25_million": 1.0,
    "actual_2023_24_million": -1.0
  },
  "latest_functional": {
    "fiscal_year": "2024-25",
    "calendar_year": 2024,
    "health_expense_million": 29560.0,
    "basic_advanced_education_expense_million": 17197.0,
    "social_services_expense_million": 8462.0,
    "other_program_expense_million": 16118.0,
    "total_program_expense_million": 71337.0,
    "debt_servicing_expense_million": 3215.0,
    "pension_provisions_recovery_million": -403.0,
    "total_expense_million": 74149.0,
    "population_july_1_thousands": 4889.0,
    "alberta_calendar_annual_cpi_growth_pct": 2.9,
    "program_component_rounding_residual_million": 0.0,
    "total_component_rounding_residual_million": 0.0,
    "program_reconciliation_status": "within ordinary integer rounding",
    "total_reconciliation_status": "within ordinary integer rounding",
    "status": "actual",
    "source_vintage": "2024-25 Final Results",
    "source_file": "Budget PDFs/2024-2025 Budget.pdf",
    "expense_pdf_page": 14,
    "economic_pdf_page": 13,
    "measure_scope": "Consolidated expense by function; not operating-only and not capital investment"
  }
}

Archived 144 source observations in two explicitly separate vintages; primary covers2013–2024. No2025 observations or invented poverty/affordability metrics.

Archived 14 current social outcome/target rows; housing breakdowns reconcile; source conflict flagged.

Archived 14 access/capacity/fee observations with explicit one post-cutoff announced fee.

Archived28 exact official MBM poverty rows, distinct2018/2023 bases, complete availableyear ranges andqualityflags; no interpolation.

2014 Canada 81.87
2014 Alberta 81.34
2015 Canada 81.92
2015 Alberta 81.45
2016 Canada 82.02
2016 Alberta 81.50
2017 Canada 81.88
2017 Alberta 81.38
2018 Canada 81.87
2018 Alberta 81.44
2019 Canada 82.22
2019 Alberta 81.96
2020 Canada 81.58
2020 Alberta 80.84
2021 Canada 81.50
2021 Alberta 80.24
2022 Canada 81.13
2022 Alberta 80.19
2023 Canada 81.68
2023 Alberta 80.71
2024 Canada 82.16
2024 Alberta 81.53
Extracted 30 crime-rate observations and 5 mental-health access observations.

Extracted108observations from13source pages; no missing observations filled.

Economic metrics: calendar_year, average_weekly_earnings, employment, employment_growth, housing_starts, primary_household_income_growth, unemployment_rate, employment_status, employment_unit, employment_growth_status, employment_growth_unit, unemployment_rate_status, unemployment_rate_unit, average_weekly_earnings_status, average_weekly_earnings_unit, primary_household_income_growth_status, primary_household_income_growth_unit, housing_starts_status, housing_starts_unit, source_file, source_pdf_page, time_basis
Built 70 function/year observations and 28 comparisons.

Built 12 figures.

In [3]:
comparison=pd.read_csv(ROOT/'data/functional_expense_baseline_comparisons.csv')
display(comparison[comparison.baseline_calendar_year.isin([2015,2018,2019])].round(2))

,baseline_calendar_year,endpoint_calendar_year,function,nominal_growth_pct,nominal_per_resident_growth_pct,cpi_adjusted_per_resident_growth_pct
0,2015,2024,Health,46.96,24.74,-1.27
1,2015,2024,Basic and advanced education,25.77,6.76,-15.50
2,2015,2024,Social services,78.07,51.16,19.63
3,2015,2024,Other programs,55.35,31.87,4.37
4,2015,2024,Total programs,45.84,23.79,-2.02
5,2015,2024,Debt servicing,314.30,251.68,178.33
6,2015,2024,Total expense,51.14,28.29,1.54
7,2018,2024,Health,34.85,18.41,-1.43
8,2018,2024,Basic and advanced education,15.82,1.70,-15.34
9,2018,2024,Social services,44.23,26.65,5.43
10,2018,2024,Other programs,35.83,19.27,-0.71
11,2018,2024,Total programs,30.89,14.93,-4.32
12,2018,2024,Debt servicing,63.12,43.23,19.23
13,2018,2024,Total expense,31.74,15.68,-3.70
14,2019,2024,Health,31.92,17.51,-0.42
15,2019,2024,Basic and advanced education,14.87,2.32,-13.29
16,2019,2024,Social services,36.42,21.52,2.98
17,2019,2024,Other programs,25.01,11.36,-5.63
18,2019,2024,Total programs,26.32,12.52,-4.65
19,2019,2024,Debt servicing,43.85,28.14,8.59
20,2019,2024,Total expense,27.02,13.15,-4.11

## Outcome evidence and matched periods

Source vintages, observation periods, eligibility and targets are retained. Current school/cohort completion ends2023–24, Grade9 achievement ends2024–25, and crime ends calendar2023.

In [4]:
health=pd.read_csv(ROOT/'research/health/extracted/health_outcomes.csv')
display(health[health.source_vintage=='2024-25'][['metric','group','period','value','unit','target','physical_pdf_page','limitations']])

,metric,group,period,value,unit,target,physical_pdf_page,limitations
0,ED initial physician assessment wait,16 largest hospital sites,2021-22,4.5,hours at 90th percentile,NaN,23,2021-22 and2022-23 revised to exclude Left Wit...
1,ED initial physician assessment wait,16 largest hospital sites,2022-23,6.2,hours at 90th percentile,NaN,23,2021-22 and2022-23 revised to exclude Left Wit...
2,ED initial physician assessment wait,16 largest hospital sites,2023-24,6.7,hours at 90th percentile,NaN,23,2021-22 and2022-23 revised to exclude Left Wit...
3,ED initial physician assessment wait,16 largest hospital sites,2024-25,7.0,hours at 90th percentile,below 2023-24 value (6.7h),23,2021-22 and2022-23 revised to exclude Left Wit...
4,EMS urgent-call response,Metro/urban,2021-22,14.6,minutes at 90th percentile,NaN,24,"Excludes interfacility transfers, other acuity..."
5,EMS urgent-call response,Metro/urban,2022-23,17.5,minutes at 90th percentile,NaN,24,"Excludes interfacility transfers, other acuity..."
6,EMS urgent-call response,Metro/urban,2023-24,13.8,minutes at 90th percentile,NaN,24,"Excludes interfacility transfers, other acuity..."
7,EMS urgent-call response,Metro/urban,2024-25,14.2,minutes at 90th percentile,below 2023-24 result,24,"Excludes interfacility transfers, other acuity..."
8,EMS urgent-call response,Communities >3000 residents,2021-22,18.6,minutes at 90th percentile,NaN,24,"Excludes interfacility transfers, other acuity..."
9,EMS urgent-call response,Communities >3000 residents,2022-23,18.9,minutes at 90th percentile,NaN,24,"Excludes interfacility transfers, other acuity..."
10,EMS urgent-call response,Communities >3000 residents,2023-24,16.3,minutes at 90th percentile,NaN,24,"Excludes interfacility transfers, other acuity..."
11,EMS urgent-call response,Communities >3000 residents,2024-25,16.4,minutes at 90th percentile,below 2023-24 result,24,"Excludes interfacility transfers, other acuity..."
12,EMS urgent-call response,Rural <3000 residents,2021-22,33.8,minutes at 90th percentile,NaN,24,"Excludes interfacility transfers, other acuity..."
13,EMS urgent-call response,Rural <3000 residents,2022-23,33.9,minutes at 90th percentile,NaN,24,"Excludes interfacility transfers, other acuity..."
14,EMS urgent-call response,Rural <3000 residents,2023-24,33.3,minutes at 90th percentile,NaN,24,"Excludes interfacility transfers, other acuity..."
15,EMS urgent-call response,Rural <3000 residents,2024-25,29.2,minutes at 90th percentile,below 2023-24 result,24,"Excludes interfacility transfers, other acuity..."
16,EMS urgent-call response,Remote,2021-22,55.4,minutes at 90th percentile,NaN,24,"Excludes interfacility transfers, other acuity..."
17,EMS urgent-call response,Remote,2022-23,61.8,minutes at 90th percentile,NaN,24,"Excludes interfacility transfers, other acuity..."
18,EMS urgent-call response,Remote,2023-24,64.9,minutes at 90th percentile,NaN,24,"Excludes interfacility transfers, other acuity..."
19,EMS urgent-call response,Remote,2024-25,52.0,minutes at 90th percentile,below 2023-24 result,24,"Excludes interfacility transfers, other acuity..."
20,Elective surgery within national wait benchmark,Hip,2020-21,51.6,percent of completed valid RTT cases,NaN,26,Completed-case denominator excludes still-wait...
21,Elective surgery within national wait benchmark,Hip,2021-22,51.2,percent of completed valid RTT cases,NaN,26,Completed-case denominator excludes still-wait...
22,Elective surgery within national wait benchmark,Hip,2022-23,43.0,percent of completed valid RTT cases,NaN,26,Completed-case denominator excludes still-wait...
23,Elective surgery within national wait benchmark,Hip,2023-24,62.4,percent of completed valid RTT cases,NaN,26,Completed-case denominator excludes still-wait...
24,Elective surgery within national wait benchmark,Hip,2024-25,72.8,percent of completed valid RTT cases,NaN,26,Completed-case denominator excludes still-wait...
25,Elective surgery within national wait benchmark,Knee,2020-21,43.3,percent of completed valid RTT cases,NaN,26,Completed-case denominator excludes still-wait...
26,Elective surgery within national wait benchmark,Knee,2021-22,39.7,percent of completed valid RTT cases,NaN,26,Completed-case denominator excludes still-wait...
27,Elective surgery within national wait benchmark,Knee,2022-23,32.5,percent of completed valid RTT cases,NaN,26,Completed-case denominator excludes still-wait...
28,Elective surgery within national wait benchmark,Knee,2023-24,53.3,percent of completed valid RTT cases,NaN,26,Completed-case denominator excludes still-wait...
29,Elective surgery within national wait benchmark,Knee,2024-25,62.5,percent of completed valid RTT cases,NaN,26,Completed-case denominator excludes still-wait...
30,Elective surgery within national wait benchmark,Cataract,2020-21,45.3,percent of completed valid RTT cases,NaN,26,Completed-case denominator excludes still-wait...
31,Elective surgery within national wait benchmark,Cataract,2021-22,64.7,percent of completed valid RTT cases,NaN,26,Completed-case denominator excludes still-wait...
32,Elective surgery within national wait benchmark,Cataract,2022-23,64.7,percent of completed valid RTT cases,NaN,26,Completed-case denominator excludes still-wait...
33,Elective surgery within national wait benchmark,Cataract,2023-24,59.7,percent of completed valid RTT cases,NaN,26,Completed-case denominator excludes still-wait...
34,Elective surgery within national wait benchmark,Cataract,2024-25,62.8,percent of completed valid RTT cases,NaN,26,Completed-case denominator excludes still-wait...
35,Diagnostic imaging within priority targets,MRI,2021-22,68.0,percent,NaN,30,"Changing urgency mix, demand, equipment and st..."
36,Diagnostic imaging within priority targets,MRI,2022-23,49.0,percent,NaN,30,"Changing urgency mix, demand, equipment and st..."
37,Diagnostic imaging within priority targets,MRI,2023-24,42.0,percent,NaN,30,"Changing urgency mix, demand, equipment and st..."
38,Diagnostic imaging within priority targets,MRI,2024-25,41.0,percent,NaN,30,"Changing urgency mix, demand, equipment and st..."
39,Diagnostic imaging within priority targets,CT,2021-22,87.0,percent,NaN,30,"Changing urgency mix, demand, equipment and st..."
40,Diagnostic imaging within priority targets,CT,2022-23,80.0,percent,NaN,30,"Changing urgency mix, demand, equipment and st..."
41,Diagnostic imaging within priority targets,CT,2023-24,80.0,percent,NaN,30,"Changing urgency mix, demand, equipment and st..."
42,Diagnostic imaging within priority targets,CT,2024-25,80.0,percent,NaN,30,"Changing urgency mix, demand, equipment and st..."
43,Unplanned medical hospital readmission within3...,included medical acute-care discharges,2020-21,13.2,percent,NaN,42,"Excludes surgery,pregnancy/childbirth,mental h..."
44,Unplanned medical hospital readmission within3...,included medical acute-care discharges,2021-22,12.9,percent,NaN,42,"Excludes surgery,pregnancy/childbirth,mental h..."
45,Unplanned medical hospital readmission within3...,included medical acute-care discharges,2022-23,12.6,percent,NaN,42,"Excludes surgery,pregnancy/childbirth,mental h..."
46,Unplanned medical hospital readmission within3...,included medical acute-care discharges,2023-24,12.7,percent,NaN,42,"Excludes surgery,pregnancy/childbirth,mental h..."
47,Unplanned medical hospital readmission within3...,included medical acute-care discharges,2024-25,12.7,percent,NaN,42,"Excludes surgery,pregnancy/childbirth,mental h..."

In [5]:
education=pd.read_csv(ROOT/'research/education_safety/current_education_observations.csv')
display(education[['metric','observation_period','value','record_kind','source_pdf_page']])

,metric,observation_period,value,record_kind,source_pdf_page
0,five_year_high_school_completion,2019-20,86.2,result,25
1,five_year_high_school_completion,2020-21,87.1,result,25
2,five_year_high_school_completion,2021-22,88.6,result,25
3,five_year_high_school_completion,2022-23,88.1,result,25
4,five_year_high_school_completion,2023-24,87.1,result,25
5,five_year_high_school_completion,2023-24,88.8,target,25
6,FNMI_five_year_high_school_completion,2019-20,68.1,result,43
7,FNMI_five_year_high_school_completion,2020-21,68.0,result,43
8,FNMI_five_year_high_school_completion,2021-22,71.3,result,43
9,FNMI_five_year_high_school_completion,2022-23,69.4,result,43
10,FNMI_five_year_high_school_completion,2023-24,69.7,result,43
11,FNMI_five_year_high_school_completion,2023-24,71.5,target,43
12,grade9_PAT_language_arts_acceptable_standard,2021-22,69.4,result,6
13,grade9_PAT_language_arts_acceptable_standard,2022-23,71.3,result,6
14,grade9_PAT_language_arts_acceptable_standard,2023-24,69.6,result,6
15,grade9_PAT_language_arts_acceptable_standard,2024-25,69.7,result,6
16,grade9_PAT_mathematics_acceptable_standard,2021-22,53.1,result,6
17,grade9_PAT_mathematics_acceptable_standard,2022-23,54.3,result,6
18,grade9_PAT_mathematics_acceptable_standard,2023-24,52.7,result,6
19,grade9_PAT_mathematics_acceptable_standard,2024-25,51.7,result,6
20,grade9_PAT_language_arts_acceptable_standard,2024-25,72.0,target,6
21,grade9_PAT_mathematics_acceptable_standard,2024-25,55.3,target,6
22,grade9_PAT_language_arts_participation,2021-22,82.3,result,7
23,grade9_PAT_language_arts_participation,2022-23,84.2,result,7
24,grade9_PAT_language_arts_participation,2023-24,83.3,result,7
25,grade9_PAT_language_arts_participation,2024-25,85.2,result,7
26,grade9_PAT_mathematics_participation,2021-22,83.0,result,7
27,grade9_PAT_mathematics_participation,2022-23,83.9,result,7
28,grade9_PAT_mathematics_participation,2023-24,84.9,result,7
29,grade9_PAT_mathematics_participation,2024-25,85.3,result,7

In [6]:
economy=pd.read_csv(ROOT/'data/economic_outcome_context.csv')
display(economy[['calendar_year','average_weekly_earnings','weekly_earnings_cpi_adjusted_2024_cad','unemployment_rate','primary_household_income_growth','primary_household_income_growth_status']])

,calendar_year,average_weekly_earnings,weekly_earnings_cpi_adjusted_2024_cad,unemployment_rate,primary_household_income_growth,primary_household_income_growth_status
0,2015,1143.0,1444.198886,6.1,3.3,historical report observation
1,2016,1116.0,1394.741792,8.2,-10.9,historical report observation
2,2017,1128.0,1387.538401,8.0,4.1,historical report observation
3,2018,1148.0,1379.043111,6.5,1.8,historical report observation
4,2019,1164.0,1373.539513,6.9,2.8,historical report observation
5,2020,1202.0,1402.947725,11.4,-4.8,historical report observation
6,2021,1226.0,1386.589140,8.6,6.6,historical report observation
7,2022,1257.0,1336.136949,5.8,10.4,historical report observation
8,2023,1283.0,1320.207000,5.9,5.7,historical report observation
9,2024,1328.0,1328.000000,7.0,7.1,estimate per a footnote; not final actual

In [7]:
social=pd.read_csv(ROOT/'research/living_standards/current_social_outcomes_2021_2024.csv')
display(social[['period','metric','value','unit','status','source_pdf_page','interpretation_limit']])

,period,metric,value,unit,status,source_pdf_page,interpretation_limit
0,2021-22,new_affordable_housing_units_and_additional_re...,2243,mixed units plus additional supported households,reported actual / prior-year result,38,"Mixed delivery/access measure, not net physica..."
1,2022-23,new_affordable_housing_units_and_additional_re...,2325,mixed units plus additional supported households,reported actual / prior-year result,38,"Mixed delivery/access measure, not net physica..."
2,2023-24,new_affordable_housing_units_and_additional_re...,2302,mixed units plus additional supported households,reported actual / prior-year result,38,"Mixed delivery/access measure, not net physica..."
3,2024-25,new_affordable_housing_units_and_additional_re...,798,mixed units plus additional supported households,reported actual / prior-year result,38,"Mixed delivery/access measure, not net physica..."
4,2024-25,housing_combined_measure_target,1500,mixed units plus additional supported households,target,38,"Target, not observed delivery"
5,2023-24,newly_built_units_breakdown,641,housing units,reported actual / prior-year result,38,Published breakdown label; do not conflate wit...
6,2023-24,additional_households_supported_rent_supplement,1661,additional supported households,reported actual / prior-year result,38,Incremental program household count; not compl...
7,2024-25,newly_built_units_breakdown,388,housing units,reported actual / prior-year result,38,Published breakdown label; do not conflate wit...
8,2024-25,additional_households_supported_rent_supplement,410,additional supported households,reported actual / prior-year result,38,Incremental program household count; not compl...
9,2020,former_CEIS_clients_employed_three_months_afte...,61,percent of former surveyed service clients,reported actual / prior-year result,49,Selected service-client survey; not provincial...
10,2021,former_CEIS_clients_employed_three_months_afte...,66,percent of former surveyed service clients,reported actual / prior-year result,49,Selected service-client survey; not provincial...
11,2022,former_CEIS_clients_employed_three_months_afte...,75,percent of former surveyed service clients,reported actual / prior-year result,49,Selected service-client survey; not provincial...
12,2023,former_CEIS_clients_employed_three_months_afte...,68,percent of former surveyed service clients,reported actual / prior-year result,49,Selected service-client survey; not provincial...
13,2024,former_CEIS_clients_employed_three_months_afte...,67,percent of former surveyed service clients,reported actual / prior-year result,49,Selected service-client survey; not provincial...

In [8]:
poverty=pd.read_csv(ROOT/'research/living_standards/mbm_poverty_all_persons_2015_2024.csv')
display(poverty[['calendar_year','geography','mbm_base','poverty_rate_pct','quality_flag','quality_definition','comparability']])
assert poverty[(poverty.mbm_base=='Market basket measure, 2018 base') & (poverty.calendar_year==2024)].empty, 'Do not invent a missing base/year'

,calendar_year,geography,mbm_base,poverty_rate_pct,quality_flag,quality_definition,comparability
0,2015,Alberta,"Market basket measure, 2018 base",9.4,D,Acceptable: CV8–16%,Keep MBM bases separate;2018–2023 estimates re...
1,2016,Alberta,"Market basket measure, 2018 base",10.1,C,Good: CV4–8%,Keep MBM bases separate;2018–2023 estimates re...
2,2017,Alberta,"Market basket measure, 2018 base",8.5,C,Good: CV4–8%,Keep MBM bases separate;2018–2023 estimates re...
3,2018,Alberta,"Market basket measure, 2018 base",9.4,C,Good: CV4–8%,Keep MBM bases separate;2018–2023 estimates re...
4,2019,Alberta,"Market basket measure, 2018 base",8.3,D,Acceptable: CV8–16%,Keep MBM bases separate;2018–2023 estimates re...
5,2020,Alberta,"Market basket measure, 2018 base",6.0,C,Good: CV4–8%,Keep MBM bases separate;2018–2023 estimates re...
6,2021,Alberta,"Market basket measure, 2018 base",8.5,C,Good: CV4–8%,Keep MBM bases separate;2018–2023 estimates re...
7,2022,Alberta,"Market basket measure, 2018 base",10.7,B,Very good: CV2–4%,Keep MBM bases separate;2018–2023 estimates re...
8,2023,Alberta,"Market basket measure, 2018 base",10.0,B,Very good: CV2–4%,Keep MBM bases separate;2018–2023 estimates re...
9,2015,Canada,"Market basket measure, 2018 base",14.5,B,Very good: CV2–4%,Keep MBM bases separate;2018–2023 estimates re...
10,2016,Canada,"Market basket measure, 2018 base",12.9,B,Very good: CV2–4%,Keep MBM bases separate;2018–2023 estimates re...
11,2017,Canada,"Market basket measure, 2018 base",11.9,A,Excellent: CV0–2%,Keep MBM bases separate;2018–2023 estimates re...
12,2018,Canada,"Market basket measure, 2018 base",11.2,B,Very good: CV2–4%,Keep MBM bases separate;2018–2023 estimates re...
13,2019,Canada,"Market basket measure, 2018 base",10.5,B,Very good: CV2–4%,Keep MBM bases separate;2018–2023 estimates re...
14,2020,Canada,"Market basket measure, 2018 base",6.5,B,Very good: CV2–4%,Keep MBM bases separate;2018–2023 estimates re...
15,2021,Canada,"Market basket measure, 2018 base",7.6,B,Very good: CV2–4%,Keep MBM bases separate;2018–2023 estimates re...
16,2022,Canada,"Market basket measure, 2018 base",10.3,A,Excellent: CV0–2%,Keep MBM bases separate;2018–2023 estimates re...
17,2023,Canada,"Market basket measure, 2018 base",10.4,A,Excellent: CV0–2%,Keep MBM bases separate;2018–2023 estimates re...
18,2020,Alberta,"Market basket measure, 2023 base",6.0,C,Good: CV4–8%,Keep MBM bases separate;2018–2023 estimates re...
19,2021,Alberta,"Market basket measure, 2023 base",8.6,C,Good: CV4–8%,Keep MBM bases separate;2018–2023 estimates re...
20,2022,Alberta,"Market basket measure, 2023 base",10.5,B,Very good: CV2–4%,Keep MBM bases separate;2018–2023 estimates re...
21,2023,Alberta,"Market basket measure, 2023 base",10.2,B,Very good: CV2–4%,Keep MBM bases separate;2018–2023 estimates re...
22,2024,Alberta,"Market basket measure, 2023 base",11.0,B,Very good: CV2–4%,Keep MBM bases separate;2018–2023 estimates re...
23,2020,Canada,"Market basket measure, 2023 base",7.0,B,Very good: CV2–4%,Keep MBM bases separate;2018–2023 estimates re...
24,2021,Canada,"Market basket measure, 2023 base",8.1,B,Very good: CV2–4%,Keep MBM bases separate;2018–2023 estimates re...
25,2022,Canada,"Market basket measure, 2023 base",10.6,A,Excellent: CV0–2%,Keep MBM bases separate;2018–2023 estimates re...
26,2023,Canada,"Market basket measure, 2023 base",11.1,A,Excellent: CV0–2%,Keep MBM bases separate;2018–2023 estimates re...
27,2024,Canada,"Market basket measure, 2023 base",11.0,A,Excellent: CV0–2%,Keep MBM bases separate;2018–2023 estimates re...

In [9]:
life=pd.read_csv(ROOT/'research/health/life_tables/life_expectancy_age0_bothsexes.csv')
life=life[(life.Element=='Life expectancy (in years) at age x (ex)') & (life.REF_DATE.between(2015,2024))].copy()
life['source_status']=life.REF_DATE.map(lambda y:'preliminary (metadata Note3)' if y in [2023,2024] else 'current source-vintage estimate')
display(life[['REF_DATE','GEO','VALUE','source_status','VECTOR']])
print('Blank raw status does not override metadata preliminary note.')

     REF_DATE      GEO  VALUE                    source_status       VECTOR
140      2015   Canada  81.92  current source-vintage estimate  v1300144478
142      2015  Alberta  81.45  current source-vintage estimate  v1300168454
144      2016   Canada  82.02  current source-vintage estimate  v1300144478
146      2016  Alberta  81.50  current source-vintage estimate  v1300168454
148      2017   Canada  81.88  current source-vintage estimate  v1300144478
150      2017  Alberta  81.38  current source-vintage estimate  v1300168454
152      2018   Canada  81.87  current source-vintage estimate  v1300144478
154      2018  Alberta  81.44  current source-vintage estimate  v1300168454
156      2019   Canada  82.22  current source-vintage estimate  v1300144478
158      2019  Alberta  81.96  current source-vintage estimate  v1300168454
160      2020   Canada  81.58  current source-vintage estimate  v1300144478
162      2020  Alberta  80.84  current source-vintage estimate  v1300168454
164      2021   Canada  81.50  current source-vintage estimate  v1300144478
166      2021  Alberta  80.24  current source-vintage estimate  v1300168454
168      2022   Canada  81.13  current source-vintage estimate  v1300144478
170      2022  Alberta  80.19  current source-vintage estimate  v1300168454
172      2023   Canada  81.68     preliminary (metadata Note3)  v1300144478
174      2023  Alberta  80.71     preliminary (metadata Note3)  v1300168454
176      2024   Canada  82.16     preliminary (metadata Note3)  v1300144478
178      2024  Alberta  81.53     preliminary (metadata Note3)  v1300168454

Blank raw status does not override metadata preliminary note.

## Standalone figures

Each figure has visible source/definition notes and an alternative description. Different outcome domains are not added or averaged.

In [10]:
display(Markdown('![Two line charts index expenses to 2018–19=100. By 2024–25 nominal health, education andsocial spending rose; CPI-adjusted per-resident health is 98.6, education 84.7, social 105.4, totalprogram 95.7.](figures/01_spending_intensity.png)'))

![Two line charts index expenses to 2018–19=100. By 2024–25 nominal health, education andsocial spending rose; CPI-adjusted per-resident health is 98.6, education 84.7, social 105.4, totalprogram 95.7.](figures/01_spending_intensity.png)

In [11]:
display(Markdown('![Horizontal bars show CPI-adjusted expense per resident: health−1.4%, basic/advancededucation−15.3%, socialservices+5.4%, totalprograms−4.3%.](figures/02_allocation_change.png)'))

![Horizontal bars show CPI-adjusted expense per resident: health−1.4%, basic/advancededucation−15.3%, socialservices+5.4%, totalprograms−4.3%.](figures/02_allocation_change.png)

In [12]:
display(Markdown('![Averageweeklyearnings 1148 CAD 2018→1328 CAD 2024 rose 15.7%nominally butfell 3.7%CPI-adjusted. Unemployment 6.5%2018→7.0%2024;2020 peak 11.4%.](figures/03_pay_and_unemployment.png)'))

![Averageweeklyearnings 1148 CAD 2018→1328 CAD 2024 rose 15.7%nominally butfell 3.7%CPI-adjusted. Unemployment 6.5%2018→7.0%2024;2020 peak 11.4%.](figures/03_pay_and_unemployment.png)

In [13]:
display(Markdown('![Separate charts show 2019–2023 violentcrimeAlberta 1462→1591 incidents/100000(+8.8%); property 5894→4752(−19.4%). Ruralratesexceedurban for both. Eachchart hasindependent yscale.](figures/04_safety.png)'))

![Separate charts show 2019–2023 violentcrimeAlberta 1462→1591 incidents/100000(+8.8%); property 5894→4752(−19.4%). Ruralratesexceedurban for both. Eachchart hasindependent yscale.](figures/04_safety.png)

In [14]:
display(Markdown('![Fiveyearcompletionoverall 86.2%2019–20→87.1%2023–24 after 88.6%peak. FNMI 68.1→69.7%. Latesttargets 88.8 overall/71.5 FNMI bothmissed. OverallincludesFNMI.](figures/05_completion.png)'))

![Fiveyearcompletionoverall 86.2%2019–20→87.1%2023–24 after 88.6%peak. FNMI 68.1→69.7%. Latesttargets 88.8 overall/71.5 FNMI bothmissed. OverallincludesFNMI.](figures/05_completion.png)

In [15]:
display(Markdown('![Grade 9 acceptable-standard languagearts 69.4→69.7%andmathematics 53.1→51.7%2021–22 to 2024–25. Latesttargets 72.0/55.3 missed; participationchanged.](figures/06_grade9.png)'))

![Grade 9 acceptable-standard languagearts 69.4→69.7%andmathematics 53.1→51.7%2021–22 to 2024–25. Latesttargets 72.0/55.3 missed; participationchanged.](figures/06_grade9.png)

In [16]:
display(Markdown('![Eligiblefirstmental-health/addictionEDvisitswithoutpriorpublicservicecontact 20.7%2019–20→19.7%2023–24; upfrom 19.5 prior year and above 17.9 matchedtarget. Lowerpreferred; not recovery.](figures/07_mental_health.png)'))

![Eligiblefirstmental-health/addictionEDvisitswithoutpriorpublicservicecontact 20.7%2019–20→19.7%2023–24; upfrom 19.5 prior year and above 17.9 matchedtarget. Lowerpreferred; not recovery.](figures/07_mental_health.png)

In [17]:
display(Markdown('![ED 90 thpercentilewait 4.5 hours 2021–22→7.0 hours 2024–25 at 16 largest sites. MRIwithinprioritytargets 68→41%; CT 87→80%. EDlatestworse than 6.7 hourpriorresult/target.](figures/08_emergency_and_imaging.png)'))

![ED 90 thpercentilewait 4.5 hours 2021–22→7.0 hours 2024–25 at 16 largest sites. MRIwithinprioritytargets 68→41%; CT 87→80%. EDlatestworse than 6.7 hourpriorresult/target.](figures/08_emergency_and_imaging.png)

In [18]:
display(Markdown('![Hip/knee/cataractshareswithinbenchmarks 2023–24→2024–25 improved 62.4→72.8%,53.3→62.5%,59.7→62.8%. EMS 90 thpercentilemetro 13.8→14.2 minworse; rural 33.3→29.2 andremote 64.9→52 improved.](figures/09_surgery_and_ems.png)'))

![Hip/knee/cataractshareswithinbenchmarks 2023–24→2024–25 improved 62.4→72.8%,53.3→62.5%,59.7→62.8%. EMS 90 thpercentilemetro 13.8→14.2 minworse; rural 33.3→29.2 andremote 64.9→52 improved.](figures/09_surgery_and_ems.png)

In [19]:
display(Markdown('![Combined new affordable units and additional rent-supported households 2243,2325,2302,798 FY 2021–22 to 2024–25. Latest 798 below 1500 target; not 798 newhomes or netstock.](figures/10_housing_support.png)'))

![Combined new affordable units and additional rent-supported households 2243,2325,2302,798 FY 2021–22 to 2024–25. Latest 798 below 1500 target; not 798 newhomes or netstock.](figures/10_housing_support.png)

In [20]:
display(Markdown('![Separate MBM bases:2018-base Alberta 9.4%2018→10.0%2023;2024 absent.2023-base Alberta 10.5%2022,10.2%2023,11.0%2024; Canada 11.0%2024. No cross-base splice or significance claim.](figures/11_poverty.png)'))

![Separate MBM bases:2018-base Alberta 9.4%2018→10.0%2023;2024 absent.2023-base Alberta 10.5%2022,10.2%2023,11.0%2024; Canada 11.0%2024. No cross-base splice or significance claim.](figures/11_poverty.png)

In [21]:
display(Markdown('![Alberta period life expectancy at birth 81.96 years 2019→80.19 years 2022→81.53 years 2024. Canada 82.16 years 2024.2023–24 preliminary; one currentvintage, separatefromarchivedAHCIP series.](figures/12_life_expectancy.png)'))

![Alberta period life expectancy at birth 81.96 years 2019→80.19 years 2022→81.53 years 2024. Canada 82.16 years 2024.2023–24 preliminary; one currentvintage, separatefromarchivedAHCIP series.](figures/12_life_expectancy.png)

## Independent verification

Direct-source second-parser checks and Decimal calculations are separate from the main extraction. Inspect review memos and source hashes for exact scope.

In [22]:
for script in ['research/budget/verify_functional_expenses_independent.py','research/living_standards/verify_living_standards.py','research/living_standards/verify_mbm_poverty.py','research/health/verify_bbox_values.py']:
    subprocess.run([sys.executable,str(ROOT/script)],cwd=ROOT,check=True)

{
  "vintages": [
    {
      "source_vintage": "2022-23",
      "observation_fiscal_year": "2022-23",
      "source_file": "2022-2023 Budget.pdf",
      "pdf_page": 13,
      "health_expense_million": "25486",
      "basic_advanced_education_expense_million": "15220",
      "social_services_expense_million": "7222",
      "other_program_expense_million": "13743",
      "total_program_expense_million": "61671",
      "debt_servicing_expense_million": "2829",
      "pension_provisions_recovery_million": "-21",
      "total_expense_million": "64479",
      "program_sum_minus_reported_total_million": "0"
    },
    {
      "source_vintage": "2023-24",
      "observation_fiscal_year": "2022-23",
      "source_file": "tbf-goa-2023-2024 Budget.pdf",
      "pdf_page": 14,
      "health_expense_million": "25486",
      "basic_advanced_education_expense_million": "15220",
      "social_services_expense_million": "7222",
      "other_program_expense_million": "13766",
      "total_program_expense_million": "61694",
      "debt_servicing_expense_million": "2829",
      "pension_provisions_recovery_million": "-21",
      "total_expense_million": "64502",
      "program_sum_minus_reported_total_million": "0"
    },
    {
      "source_vintage": "2024-25",
      "observation_fiscal_year": "2022-23",
      "source_file": "2024-2025 Budget.pdf",
      "pdf_page": 14,
      "health_expense_million": "25486",
      "basic_advanced_education_expense_million": "15220",
      "social_services_expense_million": "7222",
      "other_program_expense_million": "13769",
      "total_program_expense_million": "61691",
      "debt_servicing_expense_million": "2828",
      "pension_provisions_recovery_million": "-21",
      "total_expense_million": "64498",
      "program_sum_minus_reported_total_million": "6"
    }
  ],
  "comparison_rows": 21
}

Independent PDF reader verified144 observations, negative-income regression, and2 explicitly flagged estimated income endpoints; no2025 rows.

Independent archive reader confirms28 values/flags/vectors; two bases unspliced; unavailable endpoint regressions passed.
Second independent DictReader selector verifies geography/persons/statistic/base/scalar/units/vector/status and exact B/C CV definitions; no filled values.
PASS: 48 values; 11 table rows independently verified by word coordinates.